import { ref } from "vue";

export const notamCode = ref({
  validity: {
    0: ["Active", "bg-success"],
    1: ["Future", "bg-warning"],
    2: ["All", "bg-primary"],
  },
  type: {
    N: ["New", "bg-success"],
    C: ["Cancel", "bg-danger"],
    R: ["Replaced", "bg-warning"],
    S: ["Snow", "bg-primary"],
  },
  code23A: [
    ["Code", "Signification", "Uniform Abbreviated Phraseology"],
    ["AA", "Minimum altitude (specify en route/crossing/safe)", "mnm alt"],
    ["AC", "Class B, C, D, or E Surface Area", "ctr"],
    ["AD", "Air defense identification zone", "adiz"],
    ["AE", "Control area", "cta"],
    ["AF", "Flight information region", "fir"],
    ["AH", "Upper control area", "uta"],
    ["AL", "Minimum usable flight level", "mnm usable fl"],
    ["AN", "Area navigation route", "rnav rte"],
    ["AO", "Oceanic control area", "oca"],
    ["AP", "Reporting point (specify name or coded designator)", "rep"],
    ["AR", "ATS route (specify)", "ats route"],
    ["AT", "Terminal control area", "tma"],
    ["AU", "Upper flight information region", "uir"],
    ["AV", "Upper advisory area", "uda"],
    ["AX", "Significant point", "sig"],
    ["AZ", "Aerodrome traffic zone", "atz"],
    ["Code", "Signification", "Uniform Abbreviated Phraseology"],
    ["CA", "Air/ground facility (specify service and frequency)", "a/g fac"],
    ["CB", "Automatic dependent surveillance — broadcast (details)", "ads-b"],
    ["CC", "Automatic dependent surveillance — contract (details)", "ads-c"],
    ["CD", "Controller-pilot data link communications (details)", "cpdlc"],
    ["CE", "En route surveillance radar", "rsr"],
    ["CG", "Ground controlled approach system (GCA)", "gca"],
    ["CL", "Selective calling system (SELCAL)", "selcal"],
    ["CM", "Surface movement radar", "smr"],
    ["CP", "Precision approach radar (PAR) (specify runway)", "par"],
    [
      "CR",
      "Surveillance radar element of precision approach radar system(specify wavelength)",
      "sre",
    ],
    ["CS", "Secondary surveillance radar (SSR)", "ssr"],
    ["CT", "Terminal area surveillance radar (TAR)", "tar"],
    ["Code", "Signification", "Uniform Abbreviated Phraseology"],
    ["FA", "Aerodrome", "ad"],
    [
      "FB",
      "Friction measuring device (specify type)",
      "Friction measuring device",
    ],
    ["FC", "Ceiling measurement equipment", "ceiling measurement eqpt"],
    ["FD", "Docking system (specify AGNIS, BOLDS, etc.)", "dckg system"],
    ["FE", "Oxygen (specify type)", "oxygen"],
    ["FF", "Fire fighting and rescue", "fire and rescue"],
    ["FG", "Ground movement control", "gnd mov ctl"],
    ["FH", "Helicopter alighting area/platform", "hel alighting area"],
    ["FI", "Aircraft de-icing (specify)", "acft de-ice"],
    ["FJ", "Oils (specify type)", "oil"],
    ["FL", "Landing direction indicator", "ldi"],
    ["FM", "Meteorological service (specify type)", "met"],
    ["FO", "Fog dispersal system", "fog dispersal"],
    ["FP", "Heliport", "heliport"],
    ["FS", "Snow removal equipment", "snow removal eqpt"],
    [
      "FT",
      "Transmissometer (specify runway and, where applicable, designator(s) of transmissometer(s))",
      "transmissometer",
    ],
    ["FU", "Fuel availability", "fuel avbl"],
    ["FW", "Wind direction indicator", "wdi"],
    ["FZ", "Customs/immigration", "Cust/immigration"],
    ["Code", "Signification", "Uniform Abbreviated Phraseology"],
    [
      "GA",
      "GNSS airfield-specific operations (specify operation)",
      "gnss airfield",
    ],
    ["GW", "GNSS area-wide operations (specify operation)", "gnss area"],
    ["Code", "Signification", "Uniform Abbreviated Phraseology"],
    ["IC", "Instrument landing system (specify runway)", "ils"],
    ["ID", "DME associated with ILS", "ils dme"],
    ["IG", "Glide path (ILS) (specify runway)", "ils gp"],
    ["II", "Inner marker (ILS) (specify runway)", "ils im"],
    ["IL", "Localizer (ILS) (specify runway)", "ils loc"],
    ["IM", "Middle marker (ILS) (specify runway)", "ils mm"],
    ["IN", "Localizer (not associated with ILS)", "loc"],
    ["IO", "Outer marker (ILS) (specify runway)", "ils om"],
    ["IS", "ILS Category I (specify runway)", "ils cat I"],
    ["IT", "ILS Category II (specify runway)", "ils cat II"],
    ["IU", "ILS Category III (specify runway)", "ils cat III"],
    ["IW", "Microwave landing system (MLS) (specify runway)", "mls"],
    ["IX", "Locator, outer (ILS) (specify runway)", "ils lo"],
    ["IY", "Locator, middle (ILS) (specify runway)", "ils lm"],
    ["Code", "Signification", "Uniform Abbreviated Phraseology"],
    ["LA", "Approach lighting system (specify runway and type)", "als"],
    ["LB", "Aerodrome beacon", "abn"],
    ["LC", "Runway centre line lights (specify runway)", "rcll"],
    ["LD", "Landing direction indicator lights", "ldi lgt"],
    ["LE", "Runway edge lights (specify runway)", "redl"],
    ["LF", "Sequenced flashing lights (specify runway)", "sequenced flg lgt"],
    ["LG", "Pilot-controlled lighting", "pcl"],
    [
      "LH",
      "High intensity runway lights (specify runway)",
      "high intst rwy lgt",
    ],
    ["LI", "Runway end identifier lights (specify runway)", "rwy end id lgt"],
    ["LJ", "Runway alignment indicator lights (specify runway)", "rai lgt"],
    [
      "LK",
      "Category II components of approach lighting system (specify runway)",
      "category II components als",
    ],
    ["LL", "Low intensity runway lights (specify runway)", "low intst rwy lgt"],
    [
      "LM",
      "Medium intensity runway lights (specify runway)",
      "medium intst rwy lgt",
    ],
    ["LP", "Precision approach path indicator (specify runway)", "papi"],
    ["LR", "All landing area lighting facilities", "ldg area lgt fac"],
    ["LS", "Stopway lights (specify runway)", "stwl"],
    ["LT", "Threshold lights (specify runway)", "thr lgt"],
    ["LU", "Helicopter approach path indicator", "hapi"],
    [
      "LV",
      "Visual approach slope indicator system (specify type and runway)",
      "vasis",
    ],
    ["LW", "Heliport lighting", "heliport lgt"],
    ["LX", "Taxiway centre line lights (specify taxiway)", "twy cl lgt"],
    ["LY", "Taxiway edge lights (specify taxiway)", "twy edge lgt"],
    ["LZ", "Runway touchdown zone lights (specify runway)", "rtzl"],
    ["Code", "Signification", "Uniform Abbreviated Phraseology"],
    ["MA", "Movement area", "mov area"],
    [
      "MB",
      "Bearing strength (specify part of landing area or movement area)",
      "bearing strength",
    ],
    ["MC", "Clearway (specify runway)", "cwy"],
    ["MD", "Declared distances (specify runway)", "declared dist"],
    ["MG", "Taxiing guidance system", "tgs"],
    ["MH", "Runway arresting gear (specify runway)", "rag"],
    ["MK", "Parking area", "prkg area"],
    [
      "MM",
      "Daylight markings (specify threshold, centre line, etc.)",
      "day markings",
    ],
    ["MN", "Apron", "apron"],
    ["MO", "Stopbar (specify runway)", "rag"],
    ["MP", "Aircraft stands (specify)", "acft stand"],
    ["MR", "Runway (specify runway)", "rwy"],
    ["MS", "Stopway (specify runway)", "swy"],
    ["MT", "Threshold (specify runway)", "thr"],
    ["MU", "Runway turning bay (specify runway)", "rwy turning bay"],
    ["MW", "Strip/shoulder (specify runway)", "Strip/shoulder"],
    ["MX", "Taxiway(s) (specify)", "twy"],
    ["MY", "Rapid exit taxiway (specify)", "Rapid exit twy"],
    ["Code", "Signification", "Uniform Abbreviated Phraseology"],
    ["NA", "All radio navigation facilities (except...)", "all rdo nav fac"],
    ["NB", "Nondirectional radio beacon", "ndb"],
    ["NC", "DECCA", "decca"],
    ["ND", "Distance measuring equipment (DME)", "dme"],
    ["NF", "Fan marker", "fan mkr"],
    ["NL", "Locator (specify identification)", "l"],
    ["NM", "VOR/DME", "vor/dme"],
    ["NN", "TACAN", "tacan"],
    ["NO", "OMEGA", "omega"],
    ["NT", "VORTAC", "vortac"],
    ["NV", "VOR", "vor"],
    ["Code", "Signification", "Uniform Abbreviated Phraseology"],
    ["OA", "Aeronautical information service", "ais"],
    ["OB", "Obstacle (specify details)", "obst"],
    ["OE", "Aircraft entry requirements", "acft entry rqmnts"],
    ["OL", "Obstacle lights on ... (specify)", "obst lgt"],
    ["OR", "Rescue coordination centre", "rcc"],
    ["Code", "Signification", "Uniform Abbreviated Phraseology"],
    ["PA", "Standard instrument arrival (specify route designator)", "star"],
    ["PB", "Standard VFR arrival", "stc vfr arr"],
    ["PC", "Contingency procedures", "contingency proc"],
    ["PD", "Standard instrument departure (specify route designator)", "sid"],
    ["PE", "Standard VFR departure", "stf vfr dep"],
    ["PF", "Flow control procedure", "flow ctl proc"],
    ["PH", "Holding procedure", "hldg proc"],
    [
      "PI",
      "Instrument approach procedure (specify type and runway)",
      "instr apch proc",
    ],
    ["PK", "VFR approach procedure", "vfr apch proc"],
    ["PL", "Flight plan processing (filing and related contingency)", "fpl"],
    [
      "PM",
      "Aerodrome operating minima (specify procedure and amended minimum)",
      "opr minima",
    ],
    ["PN", "Noise operating restriction", "noise opr restrictions"],
    [
      "PO",
      "Obstacle clearance altitude and height (specify procedure)",
      "oca och",
    ],
    ["PR", "Radio failure procedure", "rdo failure proc"],
    ["PT", "Transition altitude or transition level (specify)", "ta/trl"],
    ["PU", "Missed approach procedure (specify runway)", "missed apch proc"],
    ["PX", "Minimum holding altitude (specify fix)", "mnm hldg alt"],
    ["PZ", "ADIZ procedure", "adiz proc"],
    ["Code", "Signification", "Uniform Abbreviated Phraseology"],
    ["RA", "Airspace reservation (specify)", "airspace reservation"],
    ["RD", "Danger area (specify)", "..d.."],
    ["RM", "Military operating area", "moa"],
    ["RO", "Overflying of ... (specify)", "overflying"],
    ["RP", "Prohibited area (specify)", "..p.."],
    ["RR", "Restricted area (specify)", "..r.."],
    ["RT", "Temporary restricted area (specify area)", "tempo restricted area"],
    ["Code", "Signification", "Uniform Abbreviated Phraseology"],
    ["SA", "Automatic terminal information service", "atis"],
    ["SB", "ATS reporting office", "aro"],
    ["SC", "Area control centre", "acc"],
    ["SE", "Flight information service", "fis"],
    ["SF", "Aerodrome flight information service", "afis"],
    ["SL", "Flow control centre", "flow ctl centre"],
    ["SO", "Oceanic area control centre", "oac"],
    ["SP", "Approach control service", "app"],
    ["SS", "Flight service station", "fss"],
    ["ST", "Aerodrome control tower", "twr"],
    ["SU", "Upper area control centre", "uac"],
    ["SV", "VOLMET broadcast", "volmet"],
    ["SY", "Upper advisory service (specify)", "upper advisory ser"],
    ["Code", "Signification", "Uniform Abbreviated Phraseology"],
    ["WA", "Air display", "air display"],
    ["WB", "Aerobatics", "aerobatics"],
    ["WC", "Captive balloon or kite", "captive balloon/kite"],
    ["WD", "Demolition of explosives", "demolition of explosives"],
    ["WE", "Exercises (specify)", "exer"],
    ["WF", "Air refueling", "air refueling"],
    ["WG", "Glider flying", "gld fly"],
    ["WH", "Blasting", "blasting"],
    ["WJ", "Banner/target towing", "banner/target towing"],
    ["WL", "Ascent of free balloon", "ascent of free balloon"],
    ["WM", "Missile, gun or rocket firing", "Missile/gun/rocket/frng"],
    [
      "WP",
      "Parachute jumping exercise, paragliding, or hang gliding",
      "Pje/paragliding/hang gliding",
    ],
    ["WR", "Radioactive materials or toxic chemicals (specify)", "pje"],
    ["WS", "Burning or blowing gas", "burning or blowing gas"],
    ["WT", "Mass movement of aircraft", "mass mov of acft"],
    ["WU", "Unmanned aircraft", "formation flt"],
    ["WV", "Formation flight", "formation flt"],
    ["WW", "Significant volcanic activity", "formation flt"],
    ["WY", "Aerial survey", "model flying"],
    ["WZ", "Model flying", "model flying"],
  ],
  code45A: [
    ["Code", "Signification", "Uniform Abbreviated Phraseology"],
    ["AC", "Withdrawn for maintenance", "withdrawn maint"],
    ["AD", "Available for daylight operation", "avbl day ops"],
    ["AF", "Flight checked and found reliable", "fltck okay"],
    [
      "AG",
      "Operating but ground checked only, awaiting flight check",
      "opr but gnd ck only, awaiting fltck",
    ],
    ["AH", "Hours of service are now…(specify)", "hr ser"],
    ["AK", "Resumed normal operations", "okay"],
    [
      "AL",
      "Operative (or reoperative) subject to previously published limitations/conditions",
      "Opr subj previous cond",
    ],
    ["AM", "Military operations only", "mil ops only"],
    ["AN", "Available for night operation", "avbl night ops"],
    ["AO", "Operational", "opr"],
    ["AP", "Available, prior permission required", "avbl, ppr"],
    ["AR", "Available on request", "avbl o/r"],
    ["AS", "Unserviceable", "u/s"],
    ["AU", "Not available (specify reason if appropriate)", "not avbl"],
    ["AW", "Completely withdrawn", "withdrawn"],
    [
      "AX",
      "Previously promulgated shutdown has been canceled",
      "promulgated shutdown cnl",
    ],
    ["Code", "Signification", "Uniform Abbreviated Phraseology"],
    ["CA", "Activated", "act"],
    ["CC", "Completed", "cmpl"],
    ["CD", "Deactivated", "deactivated"],
    ["CE", "Erected", "erected"],
    ["CF", "Operating frequency(ies) changed to", "opr freq changed to"],
    ["CG", "Downgraded to", "downgraded to"],
    ["CH", "Changed", "changed"],
    [
      "CI",
      "Identification or radio call sign changed to",
      "Ident/rdo call sign changed to",
    ],
    ["CL", "Realigned", "realigned"],
    ["CM", "Displaced", "displaced"],
    ["CN", "Canceled", "cnl"],
    ["CO", "Operating", "opr"],
    ["CP", "Operating on reduced power", "opr reduced pwr"],
    ["CR", "Temporarily replaced by", "tempo rplcd by"],
    ["CS", "Installed", "instl"],
    ["CT", "On test, do not use", "on test, do not use"],
    ["Code", "Signification", "Uniform Abbreviated Phraseology"],
    ["HA", "1) Poor", "2) Medium/Poor"],
    [
      "HB",
      "Friction coefficient is ... (specify friction measurement device used)",
      "friction coefficient is",
    ],
    ["HC", "Covered by compacted snow to depth of", "cov compacted snow depth"],
    ["HD", "Covered by dry snow to a depth of", "cov dry snow depth"],
    ["HE", "Covered by water to a depth of", "cov water depth"],
    ["HF", "Totally free of snow and ice", "free of sn and ice"],
    ["HG", "Grass cutting in progress", "grass cutting inpr"],
    ["HH", "Hazard due to (specify)", "hazard due"],
    ["HI", "Covered by ice", "cov ice"],
    [
      "HJ",
      "Launch planned ... (specify balloon flight identification or project code name, launch site, planned period of launch(es)-date/ time, expected climb direction, estimate time to pass 18 000 m (60 000 ft), or reaching cruise level if at or below 18 000 m (60 000 ft), together with estimated location)",
      "launch plan",
    ],
    ["HK", "Bird migration in progress", "bird migration inpr"],
    ["HL", "Snow clearance completed", "sn clr cmpl"],
    ["HM", "Marked by", "marked by"],
    [
      "HN",
      "Covered by wet snow or slush to a depth of",
      "cov wet sn/slush depth",
    ],
    ["HO", "Obscured by snow", "obscured by sn"],
    ["HP", "Snow clearance in progress", "sn clr inpr"],
    [
      "HQ",
      "Operation canceled ... (specify balloon flight identification or project code name)",
      "opr cnl",
    ],
    ["HR", "Standing water", "standing water"],
    ["HS", "Sanding in progress", "sanding inpr"],
    ["HT", "Approach according to signal area only", "apch according signal"],
    [
      "HU",
      "Launch in progress ... (specify balloon flight identification or project code name, launch site, date/time of launch(es), estimated time passing 18 000 m (60 000 ft), or reaching cruising level if at or below 18 000 m (60 000 ft), together with estimated location, estimated date/time of termination of the flight, and planned location of ground contact when applicable)",
      "launch inpr",
    ],
    ["HV", "Work completed", "work cmpl"],
    ["HW", "Work in progress", "wip"],
    ["HX", "Concentration of birds", "bird concentration"],
    ["HY", "Snow banks exist (specify height)", "sn banks hgt"],
    ["HZ", "Covered by frozen ruts and ridges", "cov frozen ruts and ridges"],
    ["Code", "Signification", "Uniform Abbreviated Phraseology"],
    ["LA", "Operating on auxiliary power supply", "opr aux pwr"],
    [
      "LB",
      "Reserved for aircraft based therein",
      "reserved for acft based therein",
    ],
    ["LC", "Closed", "clsd"],
    ["LD", "Unsafe", "unsafe"],
    ["LE", "Operating without auxiliary power supply", "opr wo aux pwr"],
    ["LF", "Interference from", "interference fm"],
    ["LG", "Operating without identification", "opr without ident"],
    ["LH", "Unserviceable for aircraft heavier than", "u/s acft heavier than"],
    ["LI", "Closed to IFR operations", "clsd ifr ops"],
    ["LK", "Operating as a fixed light", "opr as f lgt"],
    ["LL", "Usable for length of...and width of...", "usable len…/wid…"],
    ["LN", "Closed to all night operations", "clsd to all ngt ops"],
    ["LP", "Prohibited to", "prohibited to"],
    [
      "LR",
      "Aircraft restricted to runways and taxiways",
      "acft restricted to rwy and twy",
    ],
    ["LS", "Subject to interruption", "subj intrp"],
    ["LT", "Limited to", "ltd to"],
    ["LV", "Closed to VFR operations", "clsd vfr ops"],
    ["LW", "Will take place", "will take place"],
    ["LX", "Operating but caution advised due to", "opr but ctn adz due to"],
    ["Code", "Signification", "Uniform Abbreviated Phraseology"],
    [
      "XX",
      "Where 4th and 5th letter Code does not cover the situation, use XX and supplement by plain language",
      "(plain language following the NOTAM Code)",
    ],
  ],
  code23: {
    Code: ["Signification", "Uniform Abbreviated Phraseology"],
    AA: ["Minimum altitude (specify en route/crossing/safe)", "mnm alt"],
    AC: ["Class B, C, D, or E Surface Area", "ctr"],
    AD: ["Air defense identification zone", "adiz"],
    AE: ["Control area", "cta"],
    AF: ["Flight information region", "fir"],
    AG: ["AERODROMES, AIR ROUTES AND GROUND AIDS", "aga"],
    AH: ["Upper control area", "uta"],
    AL: ["Minimum usable flight level", "mnm usable fl"],
    AN: ["Area navigation route", "rnav rte"],
    AO: ["Oceanic control area", "oca"],
    AP: ["Reporting point (specify name or coded designator)", "rep"],
    AR: ["ATS route (specify)", "ats route"],
    AT: ["Terminal control area", "tma"],
    AU: ["Upper flight information region", "uir"],
    AV: ["Upper advisory area", "uda"],
    AX: ["Significant point", "sig"],
    AZ: ["Aerodrome traffic zone", "atz"],
    CA: ["Air/ground facility (specify service and frequency)", "a/g fac"],
    CB: ["Automatic dependent surveillance — broadcast (details)", "ads-b"],
    CC: ["Automatic dependent surveillance — contract (details)", "ads-c"],
    CD: ["Controller-pilot data link communications (details)", "cpdlc"],
    CE: ["En route surveillance radar", "rsr"],
    CG: ["Ground controlled approach system (GCA)", "gca"],
    CL: ["Selective calling system (SELCAL)", "selcal"],
    CM: ["Surface movement radar", "smr"],
    CO: ["Communications", "com"],
    CP: ["Precision approach radar (PAR) (specify runway)", "par"],
    CR: [
      "Surveillance radar element of precision approach radar system(specify wavelength)",
      "sre",
    ],
    CS: ["Secondary surveillance radar (SSR)", "ssr"],
    CT: ["Terminal area surveillance radar (TAR)", "tar"],
    FA: ["Aerodrome", "ad"],
    FB: [
      "Friction measuring device (specify type)",
      "Friction measuring device",
    ],
    FC: ["Ceiling measurement equipment", "ceiling measurement eqpt"],
    FD: ["Docking system (specify AGNIS, BOLDS, etc.)", "dckg system"],
    FE: ["Oxygen (specify type)", "oxygen"],
    FF: ["Fire fighting and rescue", "fire and rescue"],
    FG: ["Ground movement control", "gnd mov ctl"],
    FH: ["Helicopter alighting area/platform", "hel alighting area"],
    FI: ["Aircraft de-icing (specify)", "acft de-ice"],
    FJ: ["Oils (specify type)", "oil"],
    FL: ["Landing direction indicator", "ldi"],
    FM: ["Meteorological service (specify type)", "met"],
    FO: ["Fog dispersal system", "fog dispersal"],
    FP: ["Heliport", "heliport"],
    FS: ["Snow removal equipment", "snow removal eqpt"],
    FT: [
      "Transmissometer (specify runway and, where applicable, designator(s) of transmissometer(s))",
      "transmissometer",
    ],
    FU: ["Fuel availability", "fuel avbl"],
    FW: ["Wind direction indicator", "wdi"],
    FZ: ["Customs/immigration", "Cust/immigration"],
    GA: [
      "GNSS airfield-specific operations (specify operation)",
      "gnss airfield",
    ],
    GW: ["GNSS area-wide operations (specify operation)", "gnss area"],
    IC: ["Instrument landing system (specify runway)", "ils"],
    ID: ["DME associated with ILS", "ils dme"],
    IG: ["Glide path (ILS) (specify runway)", "ils gp"],
    II: ["Inner marker (ILS) (specify runway)", "ils im"],
    IL: ["Localizer (ILS) (specify runway)", "ils loc"],
    IM: ["Middle marker (ILS) (specify runway)", "ils mm"],
    IN: ["Localizer (not associated with ILS)", "loc"],
    IO: ["Outer marker (ILS) (specify runway)", "ils om"],
    IS: ["ILS Category I (specify runway)", "ils cat I"],
    IT: ["ILS Category II (specify runway)", "ils cat II"],
    IU: ["ILS Category III (specify runway)", "ils cat III"],
    IW: ["Microwave landing system (MLS) (specify runway)", "mls"],
    IX: ["Locator, outer (ILS) (specify runway)", "ils lo"],
    IY: ["Locator, middle (ILS) (specify runway)", "ils lm"],
    LA: ["Approach lighting system (specify runway and type)", "als"],
    LB: ["Aerodrome beacon", "abn"],
    LC: ["Runway centre line lights (specify runway)", "rcll"],
    LD: ["Landing direction indicator lights", "ldi lgt"],
    LE: ["Runway edge lights (specify runway)", "redl"],
    LF: ["Sequenced flashing lights (specify runway)", "sequenced flg lgt"],
    LG: ["Pilot-controlled lighting", "pcl"],
    LH: ["High intensity runway lights (specify runway)", "high intst rwy lgt"],
    LI: ["Runway end identifier lights (specify runway)", "rwy end id lgt"],
    LJ: ["Runway alignment indicator lights (specify runway)", "rai lgt"],
    LK: [
      "Category II components of approach lighting system (specify runway)",
      "category II components als",
    ],
    LL: ["Low intensity runway lights (specify runway)", "low intst rwy lgt"],
    LM: [
      "Medium intensity runway lights (specify runway)",
      "medium intst rwy lgt",
    ],
    LP: ["Precision approach path indicator (specify runway)", "papi"],
    LR: ["All landing area lighting facilities", "ldg area lgt fac"],
    LS: ["Stopway lights (specify runway)", "stwl"],
    LT: ["Threshold lights (specify runway)", "thr lgt"],
    LU: ["Helicopter approach path indicator", "hapi"],
    LV: [
      "Visual approach slope indicator system (specify type and runway)",
      "vasis",
    ],
    LW: ["Heliport lighting", "heliport lgt"],
    LX: ["Taxiway centre line lights (specify taxiway)", "twy cl lgt"],
    LY: ["Taxiway edge lights (specify taxiway)", "twy edge lgt"],
    LZ: ["Runway touchdown zone lights (specify runway)", "rtzl"],
    MA: ["Movement area", "mov area"],
    MB: [
      "Bearing strength (specify part of landing area or movement area)",
      "bearing strength",
    ],
    MC: ["Clearway (specify runway)", "cwy"],
    MD: ["Declared distances (specify runway)", "declared dist"],
    MG: ["Taxiing guidance system", "tgs"],
    MH: ["Runway arresting gear (specify runway)", "rag"],
    MK: ["Parking area", "prkg area"],
    MM: [
      "Daylight markings (specify threshold, centre line, etc.)",
      "day markings",
    ],
    MN: ["Apron", "apron"],
    MO: ["Stopbar (specify runway)", "rag"],
    MP: ["Aircraft stands (specify)", "acft stand"],
    MR: ["Runway (specify runway)", "rwy"],
    MS: ["Stopway (specify runway)", "swy"],
    MT: ["Threshold (specify runway)", "thr"],
    MU: ["Runway turning bay (specify runway)", "rwy turning bay"],
    MW: ["Strip/shoulder (specify runway)", "Strip/shoulder"],
    MX: ["Taxiway(s) (specify)", "twy"],
    MY: ["Rapid exit taxiway (specify)", "Rapid exit twy"],
    NA: ["All radio navigation facilities (except...)", "all rdo nav fac"],
    NB: ["Nondirectional radio beacon", "ndb"],
    NC: ["DECCA", "decca"],
    ND: ["Distance measuring equipment (DME)", "dme"],
    NF: ["Fan marker", "fan mkr"],
    NL: ["Locator (specify identification)", "l"],
    NM: ["VOR/DME", "vor/dme"],
    NN: ["TACAN", "tacan"],
    NO: ["OMEGA", "omega"],
    NT: ["VORTAC", "vortac"],
    NV: ["VOR", "vor"],
    OA: ["Aeronautical information service", "ais"],
    OB: ["Obstacle (specify details)", "obst"],
    OE: ["Aircraft entry requirements", "acft entry rqmnts"],
    OL: ["Obstacle lights on ... (specify)", "obst lgt"],
    OR: ["Rescue coordination centre", "rcc"],
    PA: ["Standard instrument arrival (specify route designator)", "star"],
    PB: ["Standard VFR arrival", "stc vfr arr"],
    PC: ["Contingency procedures", "contingency proc"],
    PD: ["Standard instrument departure (specify route designator)", "sid"],
    PE: ["Standard VFR departure", "stf vfr dep"],
    PF: ["Flow control procedure", "flow ctl proc"],
    PH: ["Holding procedure", "hldg proc"],
    PI: [
      "Instrument approach procedure (specify type and runway)",
      "instr apch proc",
    ],
    PK: ["VFR approach procedure", "vfr apch proc"],
    PL: ["Flight plan processing (filing and related contingency)", "fpl"],
    PM: [
      "Aerodrome operating minima (specify procedure and amended minimum)",
      "opr minima",
    ],
    PN: ["Noise operating restriction", "noise opr restrictions"],
    PO: [
      "Obstacle clearance altitude and height (specify procedure)",
      "oca och",
    ],
    PR: ["Radio failure procedure", "rdo failure proc"],
    PT: ["Transition altitude or transition level (specify)", "ta/trl"],
    PU: ["Missed approach procedure (specify runway)", "missed apch proc"],
    PX: ["Minimum holding altitude (specify fix)", "mnm hldg alt"],
    PZ: ["ADIZ procedure", "adiz proc"],
    RA: ["Airspace reservation (specify)", "airspace reservation"],
    RC: ["Rules of the Air and Air Traffic Services Control", "rac"],
    RD: ["Danger area (specify)", "..d.."],
    RM: ["Military operating area", "moa"],
    RO: ["Overflying of ... (specify)", "overflying"],
    RP: ["Prohibited area (specify)", "..p.."],
    RR: ["Restricted area (specify)", "..r.."],
    RT: ["Temporary restricted area (specify area)", "tempo restricted area"],
    SA: ["Automatic terminal information service", "atis"],
    SB: ["ATS reporting office", "aro"],
    SC: ["Area control centre", "acc"],
    SE: ["Flight information service", "fis"],
    SF: ["Aerodrome flight information service", "afis"],
    SL: ["Flow control centre", "flow ctl centre"],
    SO: ["Oceanic area control centre", "oac"],
    SP: ["Approach control service", "app"],
    SS: ["Flight service station", "fss"],
    ST: ["Aerodrome control tower", "twr"],
    SU: ["Upper area control centre", "uac"],
    SV: ["VOLMET broadcast", "volmet"],
    SY: ["Upper advisory service (specify)", "upper advisory ser"],
    WA: ["Air display", "air display"],
    WB: ["Aerobatics", "aerobatics"],
    WC: ["Captive balloon or kite", "captive balloon/kite"],
    WD: ["Demolition of explosives", "demolition of explosives"],
    WE: ["Exercises (specify)", "exer"],
    WF: ["Air refueling", "air refueling"],
    WG: ["Glider flying", "gld fly"],
    WH: ["Blasting", "blasting"],
    WJ: ["Banner/target towing", "banner/target towing"],
    WL: ["Ascent of free balloon", "ascent of free balloon"],
    WM: ["Missile, gun or rocket firing", "Missile/gun/rocket/frng"],
    WP: [
      "Parachute jumping exercise, paragliding, or hang gliding",
      "Pje/paragliding/hang gliding",
    ],
    WR: ["Radioactive materials or toxic chemicals (specify)", "pje"],
    WS: ["Burning or blowing gas", "burning or blowing gas"],
    WT: ["Mass movement of aircraft", "mass mov of acft"],
    WU: ["Unmanned aircraft", "formation flt"],
    WV: ["Formation flight", "formation flt"],
    WW: ["Significant volcanic activity", "formation flt"],
    WY: ["Aerial survey", "model flying"],
    WZ: ["Model flying", "model flying"],
  },
  code45: {
    Code: ["Signification", "Uniform Abbreviated Phraseology"],
    AC: ["Withdrawn for maintenance", "withdrawn maint"],
    AD: ["Available for daylight operation", "avbl day ops"],
    AF: ["Flight checked and found reliable", "fltck okay"],
    AG: [
      "Operating but ground checked only, awaiting flight check",
      "opr but gnd ck only, awaiting fltck",
    ],
    AH: ["Hours of service are now…(specify)", "hr ser"],
    AK: ["Resumed normal operations", "okay"],
    AL: [
      "Operative (or reoperative) subject to previously published limitations/conditions",
      "Opr subj previous cond",
    ],
    AM: ["Military operations only", "mil ops only"],
    AN: ["Available for night operation", "avbl night ops"],
    AO: ["Operational", "opr"],
    AP: ["Available, prior permission required", "avbl, ppr"],
    AR: ["Available on request", "avbl o/r"],
    AS: ["Unserviceable", "u/s"],
    AU: ["Not available (specify reason if appropriate)", "not avbl"],
    AW: ["Completely withdrawn", "withdrawn"],
    AX: [
      "Previously promulgated shutdown has been canceled",
      "promulgated shutdown cnl",
    ],
    CA: ["Activated", "act"],
    CC: ["Completed", "cmpl"],
    CD: ["Deactivated", "deactivated"],
    CE: ["Erected", "erected"],
    CF: ["Operating frequency(ies) changed to", "opr freq changed to"],
    CG: ["Downgraded to", "downgraded to"],
    CH: ["Changed", "changed"],
    CI: [
      "Identification or radio call sign changed to",
      "Ident/rdo call sign changed to",
    ],
    CL: ["Realigned", "realigned"],
    CM: ["Displaced", "displaced"],
    CN: ["Canceled", "cnl"],
    CO: ["Operating", "opr"],
    CP: ["Operating on reduced power", "opr reduced pwr"],
    CR: ["Temporarily replaced by", "tempo rplcd by"],
    CS: ["Installed", "instl"],
    CT: ["On test, do not use", "on test, do not use"],
    HA: ["1) Poor", "2) Medium/Poor"],
    HB: [
      "Friction coefficient is ... (specify friction measurement device used)",
      "friction coefficient is",
    ],
    HC: ["Covered by compacted snow to depth of", "cov compacted snow depth"],
    HD: ["Covered by dry snow to a depth of", "cov dry snow depth"],
    HE: ["Covered by water to a depth of", "cov water depth"],
    HF: ["Totally free of snow and ice", "free of sn and ice"],
    HG: ["Grass cutting in progress", "grass cutting inpr"],
    HH: ["Hazard due to (specify)", "hazard due"],
    HI: ["Covered by ice", "cov ice"],
    HJ: [
      "Launch planned ... (specify balloon flight identification or project code name, launch site, planned period of launch(es)-date/ time, expected climb direction, estimate time to pass 18 000 m (60 000 ft), or reaching cruise level if at or below 18 000 m (60 000 ft), together with estimated location)",
      "launch plan",
    ],
    HK: ["Bird migration in progress", "bird migration inpr"],
    HL: ["Snow clearance completed", "sn clr cmpl"],
    HM: ["Marked by", "marked by"],
    HN: [
      "Covered by wet snow or slush to a depth of",
      "cov wet sn/slush depth",
    ],
    HO: ["Obscured by snow", "obscured by sn"],
    HP: ["Snow clearance in progress", "sn clr inpr"],
    HQ: [
      "Operation canceled ... (specify balloon flight identification or project code name)",
      "opr cnl",
    ],
    HR: ["Standing water", "standing water"],
    HS: ["Sanding in progress", "sanding inpr"],
    HT: ["Approach according to signal area only", "apch according signal"],
    HU: [
      "Launch in progress ... (specify balloon flight identification or project code name, launch site, date/time of launch(es), estimated time passing 18 000 m (60 000 ft), or reaching cruising level if at or below 18 000 m (60 000 ft), together with estimated location, estimated date/time of termination of the flight, and planned location of ground contact when applicable)",
      "launch inpr",
    ],
    HV: ["Work completed", "work cmpl"],
    HW: ["Work in progress", "wip"],
    HX: ["Concentration of birds", "bird concentration"],
    HY: ["Snow banks exist (specify height)", "sn banks hgt"],
    HZ: ["Covered by frozen ruts and ridges", "cov frozen ruts and ridges"],
    LA: ["Operating on auxiliary power supply", "opr aux pwr"],
    LB: [
      "Reserved for aircraft based therein",
      "reserved for acft based therein",
    ],
    LC: ["Closed", "clsd"],
    LD: ["Unsafe", "unsafe"],
    LE: ["Operating without auxiliary power supply", "opr wo aux pwr"],
    LF: ["Interference from", "interference fm"],
    LG: ["Operating without identification", "opr without ident"],
    LH: ["Unserviceable for aircraft heavier than", "u/s acft heavier than"],
    LI: ["Closed to IFR operations", "clsd ifr ops"],
    LK: ["Operating as a fixed light", "opr as f lgt"],
    LL: ["Usable for length of...and width of...", "usable len…/wid…"],
    LN: ["Closed to all night operations", "clsd to all ngt ops"],
    LP: ["Prohibited to", "prohibited to"],
    LR: [
      "Aircraft restricted to runways and taxiways",
      "acft restricted to rwy and twy",
    ],
    LS: ["Subject to interruption", "subj intrp"],
    LT: ["Limited to", "ltd to"],
    LV: ["Closed to VFR operations", "clsd vfr ops"],
    LW: ["Will take place", "will take place"],
    LX: ["Operating but caution advised due to", "opr but ctn adz due to"],
    XX: [
      "Check plain text",
      //   "Where 4th and 5th letter Code does not cover the situation, use XX and supplement by plain language",
      "(plain language following the NOTAM Code)",
    ],
  },
});
